/// Annotations used for generated classes to give them metadata
/// Important metadata includes
/// 1- Friendly name
/// 2- Identifies if the class is generated by Nowa or not

abstract class NowaAnnotation {
  const NowaAnnotation({this.name, this.loader});

  final String? name;
  final String? loader;
}

class NowaVar extends NowaAnnotation {
  const NowaVar({super.name, super.loader});
}

class NowaFunc extends NowaAnnotation {
  const NowaFunc({super.name, super.loader});
}

class NowaClass extends NowaAnnotation {
  const NowaClass({super.name, super.loader});
}

class NowaSingleton extends NowaClass {
  const NowaSingleton({super.name, super.loader});
}
