/// Annotations used for generated classes to give them metadata
/// Important metadata includes
/// 1- Friendly name
/// 2- Identifies if the class is generated by Nowa or not

class NowaVar {
  final String? name;

  const NowaVar({this.name});
}

class NowaFunc {
  final String? name;
  final String? loader;

  const NowaFunc({this.name, this.loader});
}

class NowaClass {
  final String? name;

  const NowaClass({this.name});
}
